services:
  php:
    build: .
    container_name: grav-frankenphp
    restart: unless-stopped
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./grav:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./gpm.json:/app/gpm.json
      - ./gpm.run:/app/gpm.run
      - caddy_data:/data
      - caddy_config:/config
    environment:
      # e.g domain.com, sub.domain.com
      SERVER_NAME: localhost

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config: