services:
  php:
    build: .
    image: ${IMAGE_PREFIX:-}grav-frankenphp
    container_name: ${GRAV_CONTAINER_NAME:-}
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80" # HTTP
      - "${HTTPS_PORT:-443}:443" # HTTPS
      - "${HTTPS_PORT:-443}:443/udp" # HTTP/3
    volumes:
      # If you installed grav into a directory that is not named "grav"
      # Then change "./grav:/app" to "./your-grav-directory-name:/app" 
      - ./${GRAV_DIRECTORY:-grav}:/app
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    environment:
      # e.g domain.com, sub.domain.com
      SERVER_NAME: ${SERVER_NAME:-localhost}

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config: