services:
  php:
    build: .
    container_name: grav-frankenphp
    restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./:/app
      - ./webserver-configs/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER_NAME: ucscode.com

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config: