services:
  php:
    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true
    # (optional) create ".env" file and configure custom values
    environment:
      CADDY_GLOBAL_OPTIONS: |
        auto_https disable_redirects
      # Used internally by caddy
      SERVER_NAME: localhost:80, 127.0.0.1:80
      GRAV_ENVIRONMENT: development
    ports: !override
      - "${LOCAL_HTTP_PORT:-7000}:80"